addons:
  chrome: stable
language: node_js
services:
  - xvfb
node_js:
  - '12'
cache:
  yarn: true
cache:
  - node_modules
before_install:
  - npm i -g yarn
install:
  - yarn install
script:
  - yarn run test
  - yarn run travis
